const actionTypes = {
  GET_HOME: "GET_HOME",
  SET_CURR_SONGID: "SET_CURR_SONGID",
  SET_CURR_SONG_DATA: "SET_CURR_SONG_DATA",
  SET_CURR_ALBUMID: "SET_CURR_ALBUMID",
  SET_RECENT: "SET_RECENT",

  PLAY: "PLAY",
  SET_ALBUM: "SET_ALBUM",
  PLAYLIST: "PLAYLIST",
  LOADING: "LOADING",
  SEARCH: "SEARCH",

  LOGIN: "LOGIN",
};

export default actionTypes;
